function cache = cache_init_(nx,nu)
    if nargin < 1 || isempty(nx), nx = 0; end
    nx = double(nx);

    cache = struct( ...
        'Aall',    zeros(0, nx), ...
        'ball',    zeros(0, 1),  ...
        'row2pos', zeros(0, 1),  ...
        'idList',  zeros(0, 1),  ...
        'M2',      zeros(0, nx), ...      % (nu*nReg) x nx
        'uball',   zeros(0, nu));
end
